webtalk_init -webtalk_dir /home/gp/Facultate/CN2/Etapa 1 - RISC V/My_RISC_V_Vivado/My_RISC_V/My_RISC_V.sim/sim_1/behav/xsim/xsim.dir/test_pc_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov 26 13:57:35 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9f8a4fd0-0bdb-46c6-b397-af209ef8677f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5f37f9b3404743eca7d83c47dcd7f2df" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2600.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116712_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3992478487 -regid "" -xml /home/gp/Facultate/CN2/Etapa 1 - RISC V/My_RISC_V_Vivado/My_RISC_V/My_RISC_V.sim/sim_1/behav/xsim/xsim.dir/test_pc_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/gp/Facultate/CN2/Etapa 1 - RISC V/My_RISC_V_Vivado/My_RISC_V/My_RISC_V.sim/sim_1/behav/xsim/xsim.dir/test_pc_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/gp/Facultate/CN2/Etapa 1 - RISC V/My_RISC_V_Vivado/My_RISC_V/My_RISC_V.sim/sim_1/behav/xsim/xsim.dir/test_pc_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
